# Enable C++ support
language: cpp
sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang-3.9

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9

# Build steps
script:
  - mkdir build
  - cd build
  - clang --version
  - clang-3.9 --version


